[package]
name = "subscript_store"
version = "0.1.0"

sources = ["src"]

[[bin]]
name = "subscript_store"
entry = "main::main"

[profile.debug]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
