[package]
name = "squeeze"
version = "0.1.0"
description = "Compression algorithms for Ritz - gzip, deflate, and more"

# Source roots
sources = ["lib"]

[[lib]]
name = "squeeze"

[build]
test_only = true

# Dependencies
[dependencies]
ritzlib = { path = "../ritz/ritzlib" }
