[package]
name = "prism"
version = "0.1.0"
description = "Display server and window compositor for Harland"

sources = ["src"]

[[bin]]
name = "prism"
entry = "main::main"

[dependencies]
angelo = { path = "../angelo" }
