[package]
name = "sage"
version = "0.1.0"
description = "JavaScript engine written in Ritz"

sources = ["src"]

[[bin]]
name = "sage"
entry = "main::main"

[build]
test_dir = "test"

[dependencies]
# Uses ritzlib from RITZ_PATH
