[package]
name = "mausoleum"
version = "0.1.0"

# Source roots - directory expands to **/*.ritz
sources = ["src", "lib"]

[[bin]]
name = "mausoleum"
entry = "main::main"

# Dependencies
[dependencies]
ritzlib = { path = "../ritz/ritzlib", sources = ["."] }
cryptosec = { path = "../cryptosec" }

[profile.debug]
opt-level = 2  # O0/O1 crash LLVM 20's DAG combiner (ubuntu bug)
debug = true

[profile.release]
opt-level = 2
debug = true
