[package]
name = "s3_param_shadow"
version = "0.1.0"

sources = ["src", "lib"]

[[bin]]
name = "s3_param_shadow"

[[lib]]
name = "s3_param_shadow"

[dependencies]
ritzlib = { path = "../../../../projects/ritz/ritzlib", sources = ["."] }
s3_param_shadow = { path = ".", sources = ["lib"] }
