#!/usr/bin/env python3
"""
ritz_generator.py - Generate Ritz source files from grammar

Reads a .grammar file and generates:
1. tokens.ritz     - Token kind constants + Token struct
2. parser_core.ritz - Core parser helpers (p_peek, p_advance, parser_init)
3. parser_toplevel.ritz - Module-level parsing (fn_def, struct_def, etc.)
4. parser_stmt.ritz - Statement parsing (if, while, let, var, assign)
5. parser_expr.ritz - Expression parsing (binary, unary, postfix, primary)
6. parser_type.ritz - Type parsing (type_spec, generic_params)
7. ast_helpers.ritz - AST node constructor stubs
8. lexer_setup_gen.ritz - Lexer pattern registration

THIS FILE IS THE GENERATOR - the output files are auto-generated Ritz code.

The parser is split into modules to keep each file under 500 lines.
"""

import sys
import re
import os
from typing import List, Dict, Set, Optional, Tuple

try:
    from .grammar_parser import (
        Grammar, GrammarRule, GrammarAlt, GrammarSymbol,
        SymbolKind, TokenDef, parse_grammar_file
    )
except ImportError:
    from grammar_parser import (
        Grammar, GrammarRule, GrammarAlt, GrammarSymbol,
        SymbolKind, TokenDef, parse_grammar_file
    )


# Rule categorization for modular parser output
# These sets determine which parser_*.ritz file each rule goes into

# Core: fundamental parser infrastructure (usually empty - just helpers)
RULES_CORE = set()

# Toplevel: module-level constructs
RULES_TOPLEVEL = {
    'module', 'module_init', 'item',
    'fn_def', 'extern_fn_def', 'params', 'param', 'return_type',
    'struct_def', 'struct_fields', 'struct_field',
    'const_def', 'import_stmt', 'global_var_def', 'module_path',
    'impl_block', 'impl_methods',
}

# Stmt: statement-level constructs
RULES_STMT = {
    'block', 'stmts', 'stmt', 'control_stmt',
    'let_stmt', 'var_stmt', 'return_stmt',
    'if_stmt', 'else_clause',
    'while_stmt', 'break_stmt', 'continue_stmt',
    'assign_stmt', 'expr_stmt',
}

# Type: type-related constructs
RULES_TYPE = {
    'type_spec', 'type_name',
    'generic_params', 'type_param_list',
}

# Expr: everything else (expressions)
# Computed dynamically: any rule not in the above sets


# Map grammar token IDs to hand-written tokens.ritz IDs
# The hand-written tokens.ritz uses specific ID ranges, the grammar uses sequential IDs.
# We need the generated code to use the hand-written token ID scheme.
HAND_WRITTEN_TOKEN_IDS = {
    # Built-in
    'EOF': 0, 'ERROR': 1, 'SKIP': 2, 'NEWLINE': 3, 'INDENT': 4, 'DEDENT': 5,
    # Keywords
    'FN': 10, 'PUB': 11, 'EXTERN': 12, 'LET': 13, 'VAR': 14, 'RETURN': 15,
    'IF': 16, 'ELSE': 17, 'WHILE': 18, 'BREAK': 19, 'CONTINUE': 20,
    'CONST': 21, 'STRUCT': 22, 'IMPORT': 23, 'AS': 24, 'NIL': 25,
    'IMPL': 26, 'FOR': 27, 'TRAIT': 28, 'ENUM': 29, 'MATCH': 30,
    'DEFER': 31, 'LOOP': 32, 'UNSAFE': 33, 'IN': 34,
    'AND': 35, 'OR': 36, 'NOT': 37, 'TRUE': 38, 'FALSE': 39,
    'NULL': 40, 'SELF': 41, 'MUT': 42, 'PASS': 43, 'ASSERT': 44,
    # Type keywords
    'I8': 50, 'I16': 51, 'I32': 52, 'I64': 53,
    'U8': 54, 'U16': 55, 'U32': 56, 'U64': 57,
    'BOOL': 58, 'VOID': 59,
    # Operators
    'PLUS': 70, 'MINUS': 71, 'STAR': 72, 'SLASH': 73, 'PERCENT': 74,
    'AMP': 75, 'PIPE': 76, 'CARET': 77, 'TILDE': 78, 'AT': 79,
    'BANG': 80, 'QUESTION': 81, 'SHL': 82, 'SHR': 83,
    # Comparison
    'EQ': 85, 'NE': 86, 'LT': 87, 'GT': 88, 'LE': 89, 'GE': 90,
    # Assignment/arrows
    'ASSIGN': 95, 'PLUS_EQ': 96, 'MINUS_EQ': 97, 'STAR_EQ': 98, 'SLASH_EQ': 99,
    'ARROW': 100, 'FAT_ARROW': 101, 'DOTDOT': 102,
    # Delimiters
    'LPAREN': 110, 'RPAREN': 111, 'LBRACKET': 112, 'RBRACKET': 113,
    'LBRACE': 114, 'RBRACE': 115,
    # Punctuation
    'DOT': 120, 'COMMA': 121, 'COLON': 122, 'SEMICOLON': 123,
    'HASH': 124, 'DBLBRACKET_L': 125, 'DBLBRACKET_R': 126,
    'LBRACKET2': 125, 'RBRACKET2': 126,  # Aliases for double bracket
    # Literals
    'IDENT': 130, 'NUMBER': 131, 'STRING': 132, 'CSTRING': 133,
    'SSTRING': 134, 'CHAR': 135,
    # Whitespace
    'WHITESPACE': 140, 'COMMENT': 141,
}


class RitzGenerator:
    """Generate Ritz source files from grammar."""

    def __init__(self, grammar: Grammar):
        self.grammar = grammar
        self.output: List[str] = []
        self.rule_map: Dict[str, GrammarRule] = {r.name: r for r in grammar.rules}

    def _emit(self, line: str = ''):
        """Emit a line of Ritz code."""
        self.output.append(line)

    def _reset(self):
        self.output = []

    def _get_output(self) -> str:
        return '\n'.join(self.output)

    # =========================================================================
    # Token generation
    # =========================================================================

    def generate_tokens(self) -> str:
        """Generate tokens.ritz with constants and Token struct."""
        self._reset()
        self._emit('# Generated by ritzgen - Token definitions')
        self._emit('#')
        self._emit('# This is auto-generated code. Do not edit.')
        self._emit('')

        # Built-in token types
        self._emit('# Built-in token types')
        builtins = ['EOF', 'ERROR', 'SKIP', 'NEWLINE', 'INDENT', 'DEDENT']
        for name in builtins:
            tid = HAND_WRITTEN_TOKEN_IDS[name]
            self._emit(f'const TOK_{name}: i32 = {tid}')
        self._emit('')

        # User-defined tokens - collect all grammar tokens with known IDs,
        # sorted by ID, grouped by ID range
        all_user_toks = []
        for tok in self.grammar.tokens:
            if tok.name in builtins:
                continue
            tid = HAND_WRITTEN_TOKEN_IDS.get(tok.name)
            if tid is not None:
                all_user_toks.append((tid, tok.name))
        all_user_toks.sort()

        # Group by ID range with labels
        groups = [
            (10, 49, 'Keywords'),
            (50, 59, 'Type keywords'),
            (70, 84, 'Operators'),
            (85, 90, 'Comparison operators'),
            (95, 102, 'Assignment and arrows'),
            (110, 115, 'Delimiters'),
            (120, 126, 'Punctuation'),
            (130, 135, 'Identifiers and literals'),
            (140, 141, 'Whitespace'),
        ]

        for lo, hi, label in groups:
            toks_in_group = [(tid, name) for tid, name in all_user_toks if lo <= tid <= hi]
            if not toks_in_group:
                continue
            self._emit(f'# {label}')
            for tid, name in toks_in_group:
                self._emit(f'const TOK_{name}: i32 = {tid}')
            self._emit('')

        # Token struct
        self._emit('# Token structure')
        self._emit('struct Token')
        self._emit('    kind: i32')
        self._emit('    start: *u8')
        self._emit('    len: i32')
        self._emit('    line: i32')
        self._emit('    col: i32')
        self._emit('    # Extended fields for string content')
        self._emit('    string_val: *u8')
        self._emit('    string_len: i32')
        self._emit('')

        # token_new function
        self._emit('# Helper function to create a Token')
        self._emit('fn token_new(kind: i32, pos: i64, len: i32, line: i64, col: i64) -> Token')
        self._emit('    Token {')
        self._emit('        kind: kind,')
        self._emit('        start: null,')
        self._emit('        len: len,')
        self._emit('        line: line as i32,')
        self._emit('        col: col as i32,')
        self._emit('        string_val: null,')
        self._emit('        string_len: 0')
        self._emit('    }')

        return self._get_output()

    # =========================================================================
    # Parser generation
    # =========================================================================

    def _categorize_rule(self, rule_name: str) -> str:
        """Categorize a rule into its parser module."""
        if rule_name in RULES_TOPLEVEL:
            return 'toplevel'
        elif rule_name in RULES_STMT:
            return 'stmt'
        elif rule_name in RULES_TYPE:
            return 'type'
        else:
            return 'expr'  # Default: expressions

    def generate_parser(self) -> str:
        """Generate parser.ritz with recursive descent parser functions.

        DEPRECATED: Use generate_parser_modules() instead for modular output.
        """
        self._reset()
        self._emit('# Generated by ritzgen - Ritz recursive descent parser')
        self._emit('#')
        self._emit('# This is auto-generated code. Do not edit.')
        self._emit('')

        # Imports
        self._emit('# Import dependencies')
        self._emit('import ast')
        self._emit('import ast_helpers')
        self._emit('import tokens_gen')
        self._emit('')

        # Parser helper functions
        self._emit('# Parser helper functions')
        self._emit('')
        self._generate_parser_init()
        self._emit('')
        self._generate_parser_helpers()
        self._emit('')

        # Generate parse functions for each rule
        for rule in self.grammar.rules:
            self._generate_parse_function(rule)
            self._emit('')

        return self._get_output()

    def generate_parser_modules(self) -> Dict[str, str]:
        """Generate modular parser files.

        Returns a dict mapping filename to content:
        - parser_core.ritz - Core helpers (p_peek, p_advance, parser_init)
        - parser_toplevel.ritz - Module-level constructs
        - parser_stmt.ritz - Statement parsing
        - parser_expr.ritz - Expression parsing
        - parser_type.ritz - Type parsing
        """
        result = {}

        # Categorize rules
        rules_by_category: Dict[str, List[GrammarRule]] = {
            'toplevel': [],
            'stmt': [],
            'type': [],
            'expr': [],
        }

        for rule in self.grammar.rules:
            cat = self._categorize_rule(rule.name)
            rules_by_category[cat].append(rule)

        # Generate parser_core.ritz
        result['parser_core.ritz'] = self._generate_parser_core()

        # Generate parser_toplevel.ritz
        result['parser_toplevel.ritz'] = self._generate_parser_module(
            'toplevel', 'Module-level constructs',
            rules_by_category['toplevel'],
            imports=['ast', 'ast_helpers', 'tokens', 'parser_core', 'parser_stmt', 'parser_type', 'parser_expr']
        )

        # Generate parser_stmt.ritz
        result['parser_stmt.ritz'] = self._generate_parser_module(
            'stmt', 'Statement parsing',
            rules_by_category['stmt'],
            imports=['ast', 'ast_helpers', 'tokens', 'parser_core', 'parser_expr']
        )

        # Generate parser_expr.ritz
        result['parser_expr.ritz'] = self._generate_parser_module(
            'expr', 'Expression parsing',
            rules_by_category['expr'],
            imports=['ast', 'ast_helpers', 'tokens', 'parser_core', 'parser_type']
        )

        # Generate parser_type.ritz
        result['parser_type.ritz'] = self._generate_parser_module(
            'type', 'Type parsing',
            rules_by_category['type'],
            imports=['ast', 'ast_helpers', 'tokens', 'parser_core']
        )

        return result

    def _generate_parser_core(self) -> str:
        """Generate parser_core.ritz with core parser infrastructure."""
        self._reset()
        self._emit('# Generated by ritzgen - Parser core infrastructure')
        self._emit('#')
        self._emit('# This is auto-generated code. Do not edit.')
        self._emit('# Contains: parser_init, p_peek, p_advance, p_expect, p_current_token')
        self._emit('')

        # Imports
        self._emit('# Import dependencies')
        self._emit('import ast')
        self._emit('import tokens_gen')
        self._emit('')

        # Generate parser_init and helpers
        self._generate_parser_init()
        self._emit('')
        self._generate_parser_helpers()

        return self._get_output()

    def _generate_parser_module(self, name: str, description: str,
                                 rules: List[GrammarRule],
                                 imports: List[str]) -> str:
        """Generate a parser module file with specified rules."""
        self._reset()
        self._emit(f'# Generated by ritzgen - Parser {name}: {description}')
        self._emit('#')
        self._emit('# This is auto-generated code. Do not edit.')
        self._emit('')

        # Imports
        self._emit('# Import dependencies')
        for imp in imports:
            self._emit(f'import {imp}')
        self._emit('')

        # Generate parse functions for each rule
        for rule in rules:
            self._generate_parse_function(rule)
            self._emit('')

        return self._get_output()

    def _generate_parser_init(self):
        self._emit('fn parser_init(p: *Parser, tokens: *Token, count: i32, arena_ptr: *u8)')
        self._emit('    p.tokens = tokens')
        self._emit('    p.token_count = count')
        self._emit('    p.pos = 0')
        self._emit('    p.error = 0')
        self._emit('    p.error_msg = null')
        self._emit('    p.heap_base = arena_ptr')
        self._emit('    p.heap_offset = 0')
        self._emit('    p.module = null')
        self._emit('    # Initialize all remaining Parser fields to prevent garbage values')
        self._emit('    p.last_type_name = null')
        self._emit('    p.last_type_name_len = 0')
        self._emit('    p.last_pointee_type = 0')
        self._emit('    p.last_array_size = 0')
        self._emit('    p.last_array_elem_type = 0')
        self._emit('    p.last_array_elem_type_name = null')
        self._emit('    p.last_array_elem_type_name_len = 0')
        self._emit('    p.fn_return_type_name = null')
        self._emit('    p.fn_return_type_name_len = 0')
        self._emit('    p.last_call_type_suffix = null')
        self._emit('    p.last_call_type_suffix_len = 0')
        self._emit('    p.last_ref_inner_type = 0')
        self._emit('    # Conditional-compilation skip flag. MUST be zeroed — if left')
        self._emit('    # garbage we drop every parsed item and produce an empty module.')
        self._emit('    # Symptom: with RITZ_PATH set (different heap layout), the first')
        self._emit('    # parsed fn lands on a non-zero skip_item and silently disappears,')
        self._emit('    # leaving callers with extern declarations only at link time.')
        self._emit('    p.skip_item = 0')

    def _generate_parser_helpers(self):
        self._emit('fn p_peek(p: *Parser) -> i32')
        self._emit('    if p.pos >= p.token_count')
        self._emit('        return TOK_EOF')
        self._emit('    return (p.tokens + p.pos).kind')
        self._emit('')
        self._emit('fn p_advance(p: *Parser) -> i32')
        self._emit('    let k: i32 = p_peek(p)')
        self._emit('    if p.pos < p.token_count')
        self._emit('        p.pos = p.pos + 1')
        self._emit('    return k')
        self._emit('')
        self._emit('fn p_expect(p: *Parser, kind: i32) -> i32')
        self._emit('    if p_peek(p) == kind')
        self._emit('        p_advance(p)')
        self._emit('        return 1')
        self._emit('    return 0')
        self._emit('')
        self._emit('fn p_current_token(p: *Parser) -> Token')
        self._emit('    if p.pos >= p.token_count')
        self._emit('        var eof: Token')
        self._emit('        eof.kind = TOK_EOF')
        self._emit('        eof.start = null')
        self._emit('        eof.len = 0')
        self._emit('        eof.line = 0')
        self._emit('        eof.col = 0')
        self._emit('        return eof')
        self._emit('    return *(p.tokens + p.pos)')

    def _get_return_type(self, rule: GrammarRule) -> str:
        """Get the Ritz return type for a rule."""
        if rule.return_type:
            return rule.return_type
        # Rules with no explicit return type that are "void-like"
        # Check if all alts are side-effect-only (actions that don't return)
        return 'i32'

    def _get_default_return(self, rule: GrammarRule) -> str:
        """Get the default null/zero return for a rule's type."""
        rt = self._get_return_type(rule)
        if rt.startswith('*'):
            return 'null'
        elif rt == 'Token':
            return 'p_current_token(p)'  # Return a dummy token
        elif rt == 'i32':
            return '0'
        return 'null'

    def _symbol_type(self, sym: GrammarSymbol, rule_context: str) -> str:
        """Determine the Ritz type for a parsed symbol result."""
        base_name = sym.name
        if base_name.isupper():
            # Terminal — always Token
            return 'Token'
        # Nonterminal — look up the rule
        if base_name in self.rule_map:
            r = self.rule_map[base_name]
            if r.return_type:
                return r.return_type
        return 'i32'

    def _symbol_default(self, sym: GrammarSymbol) -> str:
        """Get the default/null value for a symbol type."""
        ty = self._symbol_type(sym, '')
        if ty.startswith('*'):
            return 'null'
        elif ty == 'Token':
            return 'p_current_token(p)'
        return '0'

    def _is_nullable_rule(self, rule_name: str) -> bool:
        """Check if a rule can match empty (has an epsilon/empty alternative)."""
        if rule_name not in self.rule_map:
            return False
        rule = self.rule_map[rule_name]
        for alt in rule.alternatives:
            if len(alt.symbols) == 0:
                return True
        return False

    def _generate_parse_function(self, rule: GrammarRule):
        """Generate a parse_<name>() function for one grammar rule."""
        rt = self._get_return_type(rule)
        default_ret = self._get_default_return(rule)

        self._emit(f'fn parse_{rule.name}(p: *Parser) -> {rt}')
        self._emit(f'    let start_pos: i32 = p.pos')
        self._emit('')

        for alt_idx, alt in enumerate(rule.alternatives):
            if alt_idx > 0:
                # Reset for next alternative
                self._emit('')
                self._emit('    # Try next alternative')
                self._emit('    p.pos = start_pos')
                self._emit('    p.error = 0')
                self._emit('')

            self._emit(f'    # Alternative {alt_idx + 1}')
            self._generate_alternative(rule, alt, alt_idx, default_ret)

        # Recovery directive: when all alternatives failed and we're not
        # at EOF, skip forward to the next "anchor" token from the rule's
        # recovery set, clear the error, and return.  For i32-returning
        # rules (typical: `item`) we return 1 to signal "progress made"
        # so the enclosing star/plus loop in the caller continues.
        # For other return types we return the default (null / 0).
        recovery_tokens = self.grammar.recovery.get(rule.name)
        if recovery_tokens:
            recovery_ret = '1' if rt == 'i32' else default_ret
            self._emit('')
            self._emit('    # Recovery: skip to next anchor token, report progress.')
            self._emit('    if p.pos < p.token_count')
            self._emit('        p.pos = p.pos + 1')
            self._emit('        while p.pos < p.token_count')
            self._emit('            let t: Token = p_current_token(p)')
            for tok in recovery_tokens:
                self._emit(f'            if t.kind == TOK_{tok}')
                self._emit('                break')
            self._emit('            p.pos = p.pos + 1')
            self._emit('        p.error = 0')
            self._emit(f'        return {recovery_ret}')

        # Final return
        self._emit('')
        self._emit(f'    if p.error == 0')
        self._emit(f'        return {default_ret}')
        self._emit(f'    return {default_ret}')

    def _generate_alternative(self, rule: GrammarRule, alt: GrammarAlt,
                              alt_idx: int, default_ret: str):
        """Generate code for one alternative of a grammar rule.

        Follows the exact pattern from ritz1_archive/src/parser_gen.ritz:

        For a single-alt rule like fn_def (FN IDENT generic_params? ...):
            result_1 = p_current_token(p)
            if p_expect(p, TOK_FN) == 0
                p.error = 1
            if p.error == 0
                result_2 = p_current_token(p)
                if p_expect(p, TOK_IDENT) == 0
                    p.error = 1
            result_3 = null
            if p.error == 0
                result_3 = parse_generic_params(p)  # optional
                p.error = 0
            ...
            if p.error == 0
                return <action>

        For a multi-alt rule like params:
            result_a1_1 = parse_param(p)
            if p.error != 0
                p.pos = start_pos
            if p.error == 0
                result_a1_2 = p_current_token(p)
                if p_expect(p, TOK_COMMA) == 0
                    p.error = 1
                    p.pos = start_pos
            ...
        """
        is_multi_alt = len(rule.alternatives) > 1

        # Determine if this is a void-action rule (like item)
        is_void_action_rule = (
            alt.action and
            rule.return_type is None and
            self._action_is_void_call(alt.action)
        )

        # Variable prefix: multi-alt uses result_aN_ to avoid redeclaration
        prefix = f'result_a{alt_idx+1}_' if is_multi_alt else 'result_'

        symbols = alt.symbols

        # Emit variable declarations
        for i, sym in enumerate(symbols):
            var_name = f'{prefix}{i+1}'
            var_type = self._symbol_type(sym, rule.name)
            if sym.kind == SymbolKind.STAR:
                pass  # Star symbols don't need variables
            else:
                self._emit(f'    var {var_name}: {var_type}')

        if symbols:
            self._emit('')

        # Parse each symbol
        # Track whether we've seen the first "required" symbol
        # After the first required symbol, all subsequent symbols are guarded by
        # `if p.error == 0`
        had_first_required = False

        for i, sym in enumerate(symbols):
            var_name = f'{prefix}{i+1}'

            if sym.kind == SymbolKind.TERMINAL:
                if not had_first_required:
                    # First terminal in this alternative
                    self._emit(f'    {var_name} = p_current_token(p)')
                    self._emit(f'    if p_expect(p, TOK_{sym.name}) == 0')
                    self._emit(f'        p.error = 1')
                    if is_multi_alt:
                        self._emit(f'        p.pos = start_pos')
                    had_first_required = True
                else:
                    # Subsequent terminal — guarded
                    self._emit(f'    if p.error == 0')
                    self._emit(f'        {var_name} = p_current_token(p)')
                    self._emit(f'        if p_expect(p, TOK_{sym.name}) == 0')
                    self._emit(f'            p.error = 1')
                    if is_multi_alt:
                        self._emit(f'            p.pos = start_pos')

            elif sym.kind == SymbolKind.NONTERMINAL:
                if not had_first_required:
                    # First nonterminal
                    self._emit(f'    {var_name} = parse_{sym.name}(p)')
                    if is_multi_alt:
                        self._emit(f'    if p.error != 0')
                        self._emit(f'        p.pos = start_pos')
                    had_first_required = True
                else:
                    # Subsequent nonterminal — guarded
                    self._emit(f'    if p.error == 0')
                    self._emit(f'        {var_name} = parse_{sym.name}(p)')
                    if is_multi_alt:
                        self._emit(f'        if p.error != 0')
                        self._emit(f'            p.pos = start_pos')

            elif sym.kind == SymbolKind.OPTIONAL:
                sym_type = self._symbol_type(sym, rule.name)
                default = 'null' if sym_type.startswith('*') else '0 as i32'
                self._emit(f'    {var_name} = {default}')
                if sym.name.isupper():
                    # Optional terminal — peek-based
                    self._emit(f'    if p.error == 0')
                    self._emit(f'        if p_peek(p) == TOK_{sym.name}')
                    self._emit(f'            {var_name} = p_current_token(p)')
                    self._emit(f'            p_advance(p)')
                else:
                    # Optional nonterminal — parse and reset error
                    self._emit(f'    if p.error == 0')
                    self._emit(f'        {var_name} = parse_{sym.name}(p)  # optional')
                    self._emit(f'        p.error = 0')

            elif sym.kind == SymbolKind.STAR:
                # Star (zero or more): loop
                if sym.name.isupper():
                    self._emit(f'    while 1 == 1')
                    self._emit(f'        if p_peek(p) != TOK_{sym.name}')
                    self._emit(f'            break')
                    self._emit(f'        p_advance(p)')
                else:
                    self._emit(f'    while 1 == 1')
                    self._emit(f'        if parse_{sym.name}(p) == 0')
                    self._emit(f'            p.error = 0')
                    self._emit(f'            break')

        # Handle action
        if alt.action:
            action_code = self._translate_action(alt.action, prefix, symbols)

            if is_void_action_rule:
                # Void action (e.g., module_add_fn) — side effect only
                self._emit(f'    if p.error == 0')
                self._emit(f'        {action_code}')
                # For item-like rules, check progress
                if is_multi_alt:
                    self._emit(f'    if p.pos > start_pos')
                    self._emit(f'        return 1')
            else:
                # Return-type action
                self._emit(f'    if p.error == 0')
                self._emit(f'        return {action_code}')
        elif len(symbols) == 1 and symbols[0].kind == SymbolKind.NONTERMINAL:
            # Single nonterminal, pass-through (e.g., stmt -> let_stmt)
            var_name = f'{prefix}1'
            self._emit(f'    if p.error == 0')
            self._emit(f'        return {var_name}')
        elif len(symbols) == 0 and alt.action:
            # Empty alternative with action (already handled above)
            pass

    def _action_is_void_call(self, action: str) -> bool:
        """Check if action is a void function call (e.g. module_add_fn(...))."""
        action = action.strip()
        void_prefixes = ['module_add_']
        for pfx in void_prefixes:
            if action.startswith(pfx):
                return True
        return False

    def _translate_action(self, action: str, prefix: str, symbols: List[GrammarSymbol]) -> str:
        """Translate a semantic action from grammar syntax to Ritz code.

        $N references become result_N (or result_aN_N for multi-alt)
        $N.start, $N.len etc. become result_N.start, result_N.len
        p.module stays as-is
        null → null
        0 as *Type → 0 as *Type (stays as-is)
        """
        result = action.strip()

        # Replace $N.field references first (before bare $N)
        def replace_dollar_field(m):
            n = int(m.group(1))
            field = m.group(2)
            return f'{prefix}{n}.{field}'

        result = re.sub(r'\$(\d+)\.(\w+(?:\.\w+)*)', replace_dollar_field, result)

        # Replace bare $N references
        def replace_dollar(m):
            n = int(m.group(1))
            return f'{prefix}{n}'

        result = re.sub(r'\$(\d+)', replace_dollar, result)

        # Clean up: 0 as *Foo → null
        result = result.replace('0 as *StructField', 'null')
        result = result.replace('0 as *Stmt', 'null')
        result = result.replace('0 as *Expr', 'null')
        result = result.replace('0 as *ImportPath', 'null')
        result = result.replace('0 as *BinaryOp', 'null')
        result = result.replace('0 as *CastTail', 'null')
        result = result.replace('0 as *PostfixOp', 'null')
        result = result.replace('0 as *FieldInit', 'null')
        result = result.replace('0 as *FnDef', 'null')
        result = result.replace('0 as *u8', 'null')

        return result

    # =========================================================================
    # AST helpers generation
    # =========================================================================

    def generate_ast_helpers(self) -> str:
        """Generate ast_helpers.ritz - copy from archive reference."""
        self._reset()
        self._emit('# Generated by ritzgen - AST Helper Functions for Generated Parser')
        self._emit('#')
        self._emit('# These functions are called by the parser generated from ritz1.grammar.')
        self._emit('# They allocate AST nodes using malloc from ritzlib.memory.')
        self._emit('')
        self._emit('# Import AST types and memory allocator')
        self._emit('import ast')
        self._emit('import ritzlib.memory')
        self._emit('')

        # Collect all function names referenced in actions
        func_names: Set[str] = set()
        for rule in self.grammar.rules:
            for alt in rule.alternatives:
                if alt.action:
                    # Extract function calls from action
                    for m in re.finditer(r'([a-z_][a-z0-9_]*)\s*\(', alt.action):
                        func_names.add(m.group(1))

        # Remove parse_int since that's a utility, not a constructor
        # Also skip p_* helper functions
        func_names -= {'parse_int', 'p_peek', 'p_advance', 'p_expect', 'p_current_token'}

        # The ast_helpers file is complex enough that we should emit the full
        # proven implementation from the archive. The function signatures must
        # match exactly what the grammar actions call.
        # We emit a note that this should be copied from the archive.
        self._emit('# =============================================================================')
        self._emit('# Parser allocation (using malloc)')
        self._emit('# =============================================================================')
        self._emit('')
        self._emit('fn parser_alloc(p: *Parser, size: i64) -> *u8')
        self._emit('    return malloc(size)')
        self._emit('')

        self._emit('# =============================================================================')
        self._emit('# Functions called by generated parser:')
        for fn in sorted(func_names):
            self._emit(f'#   {fn}()')
        self._emit('# =============================================================================')
        self._emit('')
        self._emit('# NOTE: The implementations for these functions should be copied from')
        self._emit('# ritz1_archive/src/ast_helpers.ritz which contains the proven, working code.')
        self._emit('# The function signatures must match exactly what the grammar actions call.')

        return self._get_output()

    # =========================================================================
    # Lexer setup generation
    # =========================================================================

    def generate_lexer_setup(self) -> str:
        """Generate lexer_setup_gen.ritz."""
        self._reset()
        self._emit('# Generated by ritzgen - Lexer setup')
        self._emit('#')
        self._emit('# This is auto-generated code. Do not edit.')
        self._emit('')
        self._emit('import tokens_gen')
        self._emit('import nfa')
        self._emit('import lexer_nfa')
        self._emit('')
        self._emit('# Initialize lexer with token patterns from grammar')
        self._emit('fn setup_lexer(lex: *Lexer, nfa_storage: *NFA, patterns_storage: *TokenPattern, states_storage: *NFAState, trans_storage: *Transition) -> i32')
        self._emit('    # Initialize NFA storage')
        self._emit('    nfa_init(nfa_storage, states_storage, trans_storage)')
        self._emit('')
        self._emit('    # Initialize lexer')
        self._emit('    lexer_init(lex, null, 0, nfa_storage, patterns_storage)')
        self._emit('')

        # Group tokens: keywords first (is_keyword=1), then operators (is_keyword=1),
        # then regex patterns (is_keyword=0)
        for tok in self.grammar.tokens:
            if tok.name in ('EOF', 'ERROR', 'SKIP', 'NEWLINE', 'INDENT', 'DEDENT'):
                continue
            if tok.name == 'WHITESPACE':
                continue  # Handled separately
            if tok.name == 'COMMENT':
                continue  # Handled separately

            tid = HAND_WRITTEN_TOKEN_IDS.get(tok.name)
            if tid is None:
                continue

            if tok.is_literal and tok.pattern:
                # Bare "..." literals lower to StrView in ritz1 — the pair
                # of `*u8 + i32 len` parameters is collapsed to a single
                # StrView at the lexer_add_pattern boundary.
                pattern = tok.pattern.replace('\\', '\\\\').replace('"', '\\"')
                self._emit(f'    lexer_add_pattern(lex, "{pattern}", TOK_{tok.name}, 1)')
            elif not tok.is_literal and tok.pattern:
                # Regex pattern — same StrView treatment as literal patterns.
                raw_pat = tok.pattern
                escaped = raw_pat.replace('\\', '\\\\').replace('"', '\\"')
                self._emit(f'    lexer_add_pattern(lex, "{escaped}", TOK_{tok.name}, 0)')

        # Add whitespace and comment patterns
        wt = self.grammar.token_map.get('WHITESPACE')
        if wt:
            raw_pat = wt.pattern
            escaped = raw_pat.replace('\\', '\\\\').replace('"', '\\"')
            self._emit(f'    lexer_add_pattern(lex, "{escaped}", TOK_WHITESPACE, 0)')

        ct = self.grammar.token_map.get('COMMENT')
        if ct:
            raw_pat = ct.pattern
            escaped = raw_pat.replace('\\', '\\\\').replace('"', '\\"')
            self._emit(f'    lexer_add_pattern(lex, "{escaped}", TOK_COMMENT, 0)')

        self._emit('')
        self._emit('    # Add whitespace as skip token')
        self._emit('    lexer_add_pattern(lex, " ", TOK_SKIP, 1)')
        self._emit('')
        self._emit('    # Finalize lexer')
        self._emit('    lexer_finalize(lex)')
        self._emit('')
        self._emit('    0')

        return self._get_output()


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Generate Ritz source from grammar')
    parser.add_argument('grammar_file', help='Path to .grammar file')
    parser.add_argument('--output-dir', default='.',
                        help='Output directory for generated files')
    parser.add_argument('--verbose', action='store_true')
    parser.add_argument('--monolithic', action='store_true',
                        help='Generate a single parser.ritz instead of modular files')

    args = parser.parse_args()

    grammar = parse_grammar_file(args.grammar_file)

    if args.verbose:
        print(f"Loaded {len(grammar.tokens)} tokens, {len(grammar.rules)} rules",
              file=sys.stderr)

    gen = RitzGenerator(grammar)

    output_dir = args.output_dir
    os.makedirs(output_dir, exist_ok=True)

    # Generate tokens.ritz
    tokens_code = gen.generate_tokens()
    tokens_path = os.path.join(output_dir, 'tokens.ritz')
    with open(tokens_path, 'w') as f:
        f.write(tokens_code + '\n')
    print(f"Generated {tokens_path}")

    # Generate parser files
    if args.monolithic:
        # Legacy: single parser.ritz file
        parser_code = gen.generate_parser()
        parser_path = os.path.join(output_dir, 'parser.ritz')
        with open(parser_path, 'w') as f:
            f.write(parser_code + '\n')
        print(f"Generated {parser_path}")
    else:
        # Modular: split into parser_core, parser_toplevel, etc.
        parser_modules = gen.generate_parser_modules()
        for filename, content in parser_modules.items():
            filepath = os.path.join(output_dir, filename)
            with open(filepath, 'w') as f:
                f.write(content + '\n')
            # Count lines for info
            line_count = content.count('\n') + 1
            print(f"Generated {filepath} ({line_count} lines)")

    # Generate ast_helpers.ritz stub (only if file doesn't exist)
    # ast_helpers.ritz is hand-written and should not be overwritten
    helpers_path = os.path.join(output_dir, 'ast_helpers.ritz')
    if not os.path.exists(helpers_path):
        helpers_code = gen.generate_ast_helpers()
        with open(helpers_path, 'w') as f:
            f.write(helpers_code + '\n')
        print(f"Generated {helpers_path} (stub)")
    else:
        print(f"Skipped {helpers_path} (hand-written, already exists)")

    # Generate lexer_setup_gen.ritz
    lexer_code = gen.generate_lexer_setup()
    lexer_path = os.path.join(output_dir, 'lexer_setup_gen.ritz')
    with open(lexer_path, 'w') as f:
        f.write(lexer_code + '\n')
    print(f"Generated {lexer_path}")


if __name__ == '__main__':
    main()
