[package]
name = "spire"
version = "0.1.0"
description = "MVRSPT Web Framework for Ritz"

sources = ["lib", "test"]

[build]
test_only = true

[[lib]]
name = "spire"

[[test]]
name = "spire-tests"
sources = ["test"]
entry = "test::main"

[dependencies]
ritzlib = { path = "../ritz/ritzlib" }
http = { path = "../http/lib" }
mausoleum = { path = "../mausoleum", sources = ["lib"] }
tome = { path = "../tome", sources = ["lib"] }
# Self-reference for internal imports when used as dependency
spire = { path = ".", sources = ["lib"] }
