[package]
name = "spire"
version = "0.1.0"
description = "MVRSPT Web Framework for Ritz"

sources = ["lib", "test"]

[build]
test_only = true

[lib]
name = "spire"

[test]
sources = ["test"]
entry = "test"

[dependencies]
ritzlib = { path = "../ritz/ritzlib" }
http = { path = "../http/lib" }
# mausoleum = { path = "../mausoleum" }  # When ready
# tome = { path = "../tome" }            # When ready
